config/routes.rb
###
# Manage用のルーティング
###
Rails.application.routes.draw do

  root :to => 'harries#index'

  devise_for :users

  resources :user_pets

  resources :posts

  resources :user_infos, only: [:index, :show, :edit, :update], param: :hash_id do
    collection do
      get ':hash_id/user_pets', to: 'user_pets#user_index', as: 'user_pets'
      get ':hash_id/posts', to: 'posts#user_index', as: 'posts'
    end
  end

  resources :harries do
    collection do
      get 'index'
      get 'firsttime'
      get 'information'
      get 'feature'
      get 'ranking'
      get 'tag'
    end
  end

  resources :comments do
    collection do
      get 'index'
      post 'create'
    end
  end

  resources :favorites do
    collection do
      get 'index'
      post 'create'
      delete 'destroy'
    end
  end

  resources :samples do
    collection do
      get 'index'
      get 'services'
      get 'contact'
      get 'sidebar'
      get 'about'
      get 'blog_home_1'
      get 'blog_home_2'
      get 'blog_post'
      get 'faq'
      get 'full_width'
      get 'portfolio_1_col'
      get 'portfolio_2_col'
      get 'portfolio_3_col'
      get 'portfolio_4_col'
      get 'portfolio_item'
      get 'pricing'
    end
  end
end

app/models/user_pet.rb
class UserPet < ApplicationRecord
  include Regexps

  belongs_to :user

  enum pet_sex: [:unknown, :male, :female]

  mount_uploader :image, ImageUploader

  # 保持できる最大数に達しているか？
  def self.has_pets_space?(user_id)
    UserPet.where(user_id: user_id).count < 10
  end

end

app/controllers/user_pets_controller.rb
class UserPetsController < ApplicationController
  layout "blog_home1"

  before_action :set_user_pet, only: [:show, :edit, :update, :destroy]

  # GET /user_pets
  def index
    @user_pets = UserPet.order(created_at: :desc).page(@page)
  end

  # GET /user_pets/user/ea703e7aa1
  def user_index
    user_id = UserInfo.find_id_by_hash(params[:hash_id])
    origin_person? user_id

    @user_pets = UserPet.where(user_id: user_id).all
    @is_ok_regist = UserPet.has_pets_space? user_id
  end

  # GET /user_pets/1
  def show
    origin_person? @user_pet.user.id
  end

  # GET /user_pets/new
  def new
    return unless signed_in?

    @user_pet = UserPet.new
  end

  # GET /user_pets/1/edit
  def edit
    return unless origin_signed_in? @user_pet.user.id
  end

  # POST /user_pets
  def create
    return unless signed_in?
    @user_pet = UserPet.new(user_pet_params)
    @user_pet.user_id = current_user.id

    unless UserPet.has_pets_space? @user_pet.user_id
      @user_pet.errors[:base] << "ペットは10匹までしか登録できません。"
      render :new
      return
    end

    if @user_pet.save
      redirect_to @user_pet, notice: 'ハリネズミを登録しました。'
    else
      render :new
    end
  end

  # PATCH/PUT /user_pets/1
  def update
    origin_signed_in?(@user_pet.user.id)

    if @user_pet.update(user_pet_params)
      redirect_to @user_pet, notice: 'ハリネズミの情報を更新しました。'
    else
      render :edit
    end
  end

  # DELETE /user_pets/1
  def destroy
    origin_signed_in?(@user_pet.user.id)

    @user_pet.destroy
    # FIXME: 次に表示するページが正しく表示されない
    redirect_to user_pets_user_infos_url(hash_id: @user_pet.user.user_info.hash_id), notice: 'ハリネズミの情報を削除しました。'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_pet
      @user_pet = UserPet.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_pet_params
      tmp_params = params.require(:user_pet).permit(:user_id, :pet_name, :pet_birthday, :pet_type, :pet_sex, :one_phrase, :image)
      tmp_params[:pet_sex] = tmp_params[:pet_sex].to_i if tmp_params[:pet_sex].present?

      tmp_params
    end
end

app/views/user_pets/_form.html.erb
<%= form_with(model: user_pet, local: true) do |form| %>
<% if user_pet.errors.any? %>
  <%= render 'common/error_explanation', form: user_pet %>
<% end %>

<div class="control-group form-group">
  <div class="controls">
  <%= form.label :image %>
  <%== big_circle_icon(user_pet.image.present? ? user_pet.image.to_s : nil, user_pet.pet_name) %>
  <%= form.file_field :image, class: "form-control" %>
  </div>
</div>

<div class="control-group form-group">
  <div class="controls">
    <%= form.label :pet_name %>
    <%= form.text_field :pet_name, id: :user_pet_pet_name, class: "form-control" %>
  </div>
</div>

<%= form.label :pet_birthday %><br>
<div class="form-inline">
  <div class="control-group form-group">
    <%== sprintf(form.date_select(
            :pet_birthday,
            {
              id: :user_pet_pet_birthday,
              use_month_numbers: true,
              start_year:        2000,
              end_year:          (Time.now.year),
              default:           Date.new(2010, 1, 1),
              date_separator:    '%s',
              discard_day:       true,
            },
            {
              class:             "form-control",
            }),
         '年 ') + '月'
    %>

  </div>
</div>

<br>

<div class="control-group form-group">
  <div class="controls">
    <%= form.label :pet_type %>
    <%= form.text_field :pet_type, id: :user_pet_pet_type, class: "form-control" %>
  </div>
</div>

<%= form.label :pet_sex %>
<br>
<div class="btn-group" data-toggle="buttons">
  <label class="btn btn-secondary <%= user_pet.unknown? ? "active" : "" %>">
    <%= form.radio_button :pet_sex, UserPet.pet_sexes["unknown"], checked: user_pet.unknown? %> <%= t('enums.user_pet.sex.unknown') %>
  </label>
  <label class="btn btn-primary <%= user_pet.male? ? "active" : "" %>">
    <%= form.radio_button :pet_sex, UserPet.pet_sexes["male"], checked: user_pet.male? %> <%= t('enums.user_pet.sex.male') %>
  </label>
  <label class="btn btn-primary <%= user_pet.female? ? "active" : "" %>">
    <%= form.radio_button :pet_sex, UserPet.pet_sexes["female"], checked: user_pet.female? %> <%= t('enums.user_pet.sex.female') %>
  </label>
</div>

<div class="control-group form-group">
  <div class="controls">
    <%= form.label :one_phrase %>
    <%= form.text_field :one_phrase, id: :user_pet_one_phrase, class: "form-control" %>
  </div>
</div>

<%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/user_pets/_show.html.erb
<%== big_circle_icon(user_pet.image.to_s, user_pet.pet_name) %>

<%== t_item_label("user_pet.pet_name", user_pet.pet_name) %>

<%== t_item_label("user_pet.pet_birthday", l(user_pet.pet_birthday, format: :birth_short)) %>

<%== t_item_label("user_pet.pet_type", user_pet.pet_type) %>

<%== t_item_label("user_pet.pet_sex", user_pet.pet_sex_i18n) %>

<%== t_item_label("user_pet.one_phrase", user_pet.one_phrase) %>

app/views/user_pets/edit.html.erb
<h1><%= t('views.user_pets.edit_title') %></h1>

<%= render 'form', user_pet: @user_pet %>

<br>

<%= link_to t('views.user_pets.show_list'), user_pets_user_infos_path(current_user.user_info.hash_id) %>

app/views/user_pets/index.html.erb
<h1 class="my-4"><%= t('views.user_pets.list_title') %></h1>

<p><%= page_entries_info @user_pets %></p>

<div class="row">

  <% @user_pets.each do |user_pet| %>
    <div class="col-lg-4 col-sm-6 mt-4">
      <a href="<%= user_pet_path user_pet.id %>">
        <div class="form-inline">
          <div class="form-group">
              <%== thumbnail_icon(user_pet.image.to_s, user_pet.pet_name) %>
          </div>
          <div class="form-group">
            <%= user_pet.pet_name %>
          </div>
        </div>
      </a>
    </div>
  <% end %>

</div>

<hr class="style17">

<!-- 挙動を確認する -->
<%= paginate @user_pets, :theme => 'twitter-bootstrap-4' %>

app/views/user_pets/new.html.erb
<h1><%= t('views.user_pets.regist_title') %></h1>

<%= render 'form', user_pet: @user_pet %>

<% if user_signed_in? %>
<%= link_to t('views.user_pets.show_list'), user_pets_user_infos_path(current_user.user_info.hash_id), class: "btn btn-link" %>
<% end %>

app/views/user_pets/show.html.erb
<% if @is_org_user %>
<%== buttons(edit_user_pet_path(@user_pet), user_pet_path(@user_pet)) %>
<% end %>

<br>
<br>

<%= render 'show', user_pet: @user_pet %>

<% if user_signed_in? %>
<%= link_to t('views.user_pets.show_list'), user_pets_user_infos_path(current_user.user_info.hash_id), class: "btn btn-link" %>
<% end %>

app/views/user_pets/user_index.html.erb
<% unless @user_pets.present? %>
<%== only_label(t('views.user_pets.regist_none_msg')) %>
<% end %>

<% @user_pets.each do |user_pet| %>

<% if @is_org_user %>
<%== buttons(edit_user_pet_path(user_pet), user_pet_path(user_pet)) %>
<% end %>

<br>
<br>

<%= render 'show', user_pet: user_pet %>

<hr class="style17">

<% end %>

<% if @is_org_user %>
	<% if @is_ok_regist %>
	<%= link_to t('views.user_pets.regist_btn'), new_user_pet_path, class: "btn btn-primary" %>
	<% else %>
  <div class="form-group row">
    <label class="col-sm-12 col-form-label"><%= t('views.user_pets.regist_over_msg') %></label>
  </div>
	<% end %>
<% end %>