config/routes.rb
###
# Manage用のルーティング
###
Rails.application.routes.draw do

  root :to => 'harries#index'

  devise_for :users

  resources :user_pets

  resources :posts

  resources :user_infos, only: [:index, :show, :edit, :update], param: :hash_id do
    collection do
      get ':hash_id/user_pets', to: 'user_pets#user_index', as: 'user_pets'
      get ':hash_id/posts', to: 'posts#user_index', as: 'posts'
    end
  end

  resources :harries do
    collection do
      get 'index'
      get 'firsttime'
      get 'information'
      get 'feature'
      get 'ranking'
      get 'tag'
    end
  end

  resources :comments do
    collection do
      get 'index'
      post 'create'
    end
  end

  resources :favorites do
    collection do
      get 'index'
      post 'create'
      delete 'destroy'
    end
  end

  resources :samples do
    collection do
      get 'index'
      get 'services'
      get 'contact'
      get 'sidebar'
      get 'about'
      get 'blog_home_1'
      get 'blog_home_2'
      get 'blog_post'
      get 'faq'
      get 'full_width'
      get 'portfolio_1_col'
      get 'portfolio_2_col'
      get 'portfolio_3_col'
      get 'portfolio_4_col'
      get 'portfolio_item'
      get 'pricing'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include Regexps

  is_impressionable # PVカウント
  is_impressionable :counter_cache => true

  acts_as_taggable # Alias for acts_as_taggable_on :tags

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :youtube_video_id, presence: true, format: { with:  REG_EN_NU_H }

  # オススメを返却する
  def self.find_recommend_posts_for_sidebar(post)
    post.find_related_tags
  end

  # ランキングを取得する
  def self.find_ranking_posts_for_sidebar(limit)
    tmp_orm = Post.order(impressions_count: :desc)

    if limit.present?
      tmp_orm.limit(limit)
    else
      tmp_orm
    end
  end


  # validate :youtube_video_id_format
  #
  # before_save :prepare_save
  #
  # youtubeのidの形式チェック
  # FIXME: 記録のために残している。不要になったら削除
  # def youtube_video_id_format
  #   target = self.youtube_video_id
  #   # URLのまま入力されている場合は、IDを抽出
  #   target.match(REG_YOUTUBE_URL) do |md|
  #     target = md[1]
  #   end

  #   unless target =~ /^\w+$/
  #     errors.add(:youtube_video_id, I18n.t("errors.messages.invalid"))
  #   end
  # end

  # save前処理
  # FIXME: 記録のために残している。不要になったら削除
  # def prepare_save
  #   # URLのまま入力されている場合は、IDを抽出
  #   self.youtube_video_id.match(REG_YOUTUBE_URL) do |md|
  #     self.youtube_video_id = md[1]
  #   end

  #   true
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout "blog_home1"

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  impressionist actions: [:show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(created_at: :desc).page(@page)

    # 検索結果の一番目でオススメを決定する
    @recommend_post = Post.find_recommend_posts_for_sidebar(@posts.first) if @posts.present?

    @ranking_post = Post.find_ranking_posts_for_sidebar(5)
  end

  # GET /posts/user/ea703e7aa1
  def user_index
    @target_user_info = UserInfo.find_user_by_hash(params[:hash_id])
    origin_person? @target_user_info[:user_id]

    @posts = Post.where(user_id: user_id).page(@page)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    origin_person? @post.user.id

    @comments, @is_favorite, @favorite_size = PostsService.show  @post

    @recommend_post = Post.find_recommend_posts_for_sidebar(@post)

    @ranking_post = Post.find_ranking_posts_for_sidebar(5)
  end

  # GET /posts/new
  def new
    return unless signed_in?

    @post = Post.new(user_id: current_user.id)
  end

  # GET /posts/1/edit
  def edit
    return unless origin_signed_in? @post.user.id
  end

  # POST /posts
  # POST /posts.json
  def create
    return unless signed_in?

    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '投稿を作成しました。' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    origin_signed_in?(@post.user.id)

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: '投稿に成功しました。' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    origin_signed_in?(@post.user.id)

    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: '投稿を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :description, :youtube_video_id, :tag_list)
    end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
<% if post.errors.any? %>
  <%= render 'common/error_explanation', form: post %>
<% end %>

<div class="control-group form-group">
  <div class="controls">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title, class: "form-control" %>
  </div>
</div>

<div class="control-group form-group">
  <div class="controls">
    <%= form.label :description %>
    <%= form.text_area :description, id: :post_description, class: "form-control" %>
  </div>
</div>

<div class="control-group form-group">
  <div class="controls">
    <%= form.label :youtube_video_id %>
    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
      <div class="input-group-addon">youtube.com/watch?v=</div>
      <%= form.text_field :youtube_video_id, id: :post_youtube_video_id, class: "form-control" %>
    </div>
  </div>
</div>

<div class="control-group form-group">
  <div class="controls">
    <%= form.label :tags %>
    <%= form.text_field :tag_list, id: :post_tag_list, class: "form-control" %>
  </div>
</div>

<%= form.submit class: "btn btn-primary" %>

<% end %>

app/views/posts/_post_list_item.html.erb
<div class="col-lg-4 col-sm-6 portfolio-item">
  <div class="card h-100">
    <a href="<%= post_path(post.id) %>"><img class="card-img-top" src="<%= "http://i.ytimg.com/vi/#{post.youtube_video_id}/sddefault.jpg" %>" alt="<%= post.title %>"></a>
    <div class="card-body movie-list-m">
      <h4 class="card-title">
        <a href="<%= post_path(post.id) %>"><%= cut_str post.title, 25 %></a>
      </h4>
      <p class="card-text">
        <a href="<%= user_info_path(post.user.user_info.hash_id) %>" class="normal"><%= post.user.user_info.nickname %></a>
        <br>
        <%= t('views.posts.show_favorite_count_msg', favorite_count: post.favorites.count) %>・<%= t('views.posts.show_impressionist_count_msg', impressionist_count: post.impressionist_count) %>・<%= t('views.posts.show_open_date_msg', open_date: l(post.created_at, format: :short)) %>
      </p>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="btn-toolbar">
  <div class="btn-group">
    <%= link_to t('views.posts.show_post_info_btn'), @post, class: "btn btn-default" %>
  </div>
</div>

<h1><%= t('views.posts.edit_title') %></h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1 class="my-4"><%= t('views.posts.list_title') %></h1>

<p><%= page_entries_info @posts %></p>

<div class="row">

  <% @posts.each do |post| %>

    <%= render 'post_list_item', post: post %>

  <% end %>

</div>

<hr class="style17">

<!-- 挙動を確認する -->
<%= paginate @posts, :theme => 'twitter-bootstrap-4' %>

app/views/posts/new.html.erb
<h1><%= t('views.posts.regist_title') %></h1>

<%= render 'form', post: @post %>

<br>

<%= link_to t('views.posts.show_list'), posts_user_infos_path(current_user.user_info.hash_id), class: "btn btn-link" %>

app/views/posts/show.html.erb
<!-- Page Content -->
<div class="container">

  <% if @is_org_user %>
  <%== buttons(edit_post_path(@post), post_path(@post)) %>
  <% end %>

  <!-- Page Heading/Breadcrumbs -->
  <h1 class="mt-4 mb-3"><%= @post.title %>
  </h1>

  <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-12">

      <!-- Preview Movie -->
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/<%= @post.youtube_video_id %>?rel=0&controls=0&fs=0&modestbranding=1" allowfullscreen></iframe>
      </div>

      <br>
      <br>

      <!-- Like -->
      <div>
        <% if user_signed_in? %>
          <% if @is_favorite %>
          <span><i id="favorite" class="fa fa-heart fa-lg"></i></span>
          <% else %>
          <span><i id="favorite-o" class="fa fa-heart-o fa-lg"></i></span>
          <% end %>
        <% end %>

        <% if @favorite_size > 0 %>
        <span id="favorite_count"><%= t('views.posts.show_favorite_count_msg', favorite_count: @favorite_size) %></span>
        <% else %>
        <span id="favorite_count"><%= t('views.posts.show_favorite_none_msg') %></span>
        <% end %>
      </div>

      <br>

      <ol class="breadcrumb">
        <li class="breadcrumb-item active">
          <span><i class="fa fa-user-circle fa-lg"></i><a href="<%= user_info_path(@post.user.user_info.hash_id) %>"><%= @post.user.user_info.nickname %></a></span>
          <!-- Date/Time -->
          <span><i class="fa fa-clock-o fa-lg"></i><%= t('views.posts.show_open_date_msg', open_date: l(@post.created_at, format: :short)) %></span>
          <span><i class="fa fa-comments fa-lg"></i><%= t('views.posts.show_comment_count_msg', comment_count: @comments.size) %></span>
          <span><i class="fa fa-tv fa-lg"></i><%= t('views.posts.show_impressionist_count_msg', impressionist_count: @post.impressionist_count) %></span>
          <br>

          <% if @post.tag_list.present? %>
          <span><i class="fa fa-tags fa-lg"></i><%= @post.tag_list %></span>
          <% end %>
        </li>
      </ol>

      <hr class="style17">

      <!-- Post Content -->
      <p class="lead"><%= @post.description %></p>

      <hr class="style17">

      <% if user_signed_in? %>

      <%= form_for(Comment.new, url: comments_path) do |comment| %>
      <!-- Comments Form -->
      <div class="card my-4">
        <h5 class="card-header"><%= t('views.posts.show_comment_title') %></h5>
        <div class="card-body">
          <form>
            <div class="form-group">
              <%= comment.text_area :comment, rows: 3, class: "form-control" %>
            </div>
            <%= comment.submit t('views.posts.show_comment_submit_btn'), class: "btn btn-primary" %>
          </form>
        </div>
      </div>
      <% end %>

      <% end %>

      <div id="comment-field">
        <% @comments.each do |comment| %>
        <!-- Single Comment -->
        <div class="media mb-4">
          <%== thumbnail_icon(comment.user.user_info.image.to_s, comment.user.user_info.nickname) %>
          <div class="media-body">
            <h5 class="mt-0"><%= comment.user.user_info.nickname %></h5>
            <%= comment.comment %>
          </div>
        </div>
        <hr>
        <% end %>
      </div>
    </div>

  </div>
  <!-- /.row -->

  <%= hidden_field_tag 'post[id]', @post.id %>
</div>
<!-- /.container -->

<script>
  (function($) {
    modules.posts.show();
  })(jQuery);
</script>

app/views/posts/user_index.html.erb
<h1 class="my-4"><%= t('views.posts.show_user_list_title', nickname: @target_user_info[:nickname]) %></h1>

<p><%= page_entries_info @posts %></p>

<div class="row">

  <% @posts.each do |post| %>

    <%= render 'post_list_item', post: post %>

  <% end %>

</div>

<hr class="style17">

<!-- 挙動を確認する -->
<%= paginate @posts, :theme => 'twitter-bootstrap-4' %>