config/routes.rb
###
# Manage用のルーティング
###
Rails.application.routes.draw do

  root :to => 'harries#index'

  devise_for :users

  resources :user_pets

  resources :posts

  resources :user_infos, only: [:index, :show, :edit, :update], param: :hash_id do
    collection do
      get ':hash_id/user_pets', to: 'user_pets#user_index', as: 'user_pets'
      get ':hash_id/posts', to: 'posts#user_index', as: 'posts'
    end
  end

  resources :harries do
    collection do
      get 'index'
      get 'firsttime'
      get 'information'
      get 'feature'
      get 'ranking'
      get 'tag'
    end
  end

  resources :comments do
    collection do
      get 'index'
      post 'create'
    end
  end

  resources :favorites do
    collection do
      get 'index'
      post 'create'
      delete 'destroy'
    end
  end

  resources :samples do
    collection do
      get 'index'
      get 'services'
      get 'contact'
      get 'sidebar'
      get 'about'
      get 'blog_home_1'
      get 'blog_home_2'
      get 'blog_post'
      get 'faq'
      get 'full_width'
      get 'portfolio_1_col'
      get 'portfolio_2_col'
      get 'portfolio_3_col'
      get 'portfolio_4_col'
      get 'portfolio_item'
      get 'pricing'
    end
  end
end

app/views/common/_error_explanation.html.erb
<div id="error_explanation">
  <div class="card">
    <h5 class="card-header"><%= t('views.common.error_field.error_title') %></h5>
    <div class="card-body">
      <div class="input-group">
        <ul>
        <% form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/common/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-success">
  <div class="container">
    <p class="m-0 text-center text-white"><%= t('views.common.footer.copyright') %></p>
  </div>
  <!-- /.container -->
</footer>

app/views/common/_header.html.erb
<header>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" class="active"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <!-- Slide One - Set the background image for this slide in the line below -->
      <div class="carousel-item active" style="background-image:url(<%= asset_path '/assets/common/header.jpg' %>); max-height: 310px;">
        <div class="carousel-caption d-none d-md-block">
        </div>
      </div>
    </div>
    <!-- 複数の画像をスライダーさせたい場合は必要
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    -->
  </div>
</header>

app/views/common/_navi.html.erb
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-harf-white fixed-top">
  <div class="container">
    <a class="navbar-brand" href="<%= harries_path %>"><%= t('views.common.navi.site_title') %></a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%= firsttime_harries_path %>"><%= t('views.common.navi.first_time_btn') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= posts_path %>"><%= t('views.common.navi.post_list_btn') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= user_pets_path %>"><%= t('views.common.navi.user_pets_list_btn') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= information_harries_path %>"><%= t('views.common.navi.show_information_btn') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= feature_harries_path %>"><%= t('views.common.navi.show_feature_btn') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= ranking_harries_path %>"><%= t('views.common.navi.show_ranking_list_btn') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= tag_harries_path %>"><%= t('views.common.navi.show_tag_list_btn') %></a>
        </li>
        <!-- ログイン -->
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%== navi_icon(current_user.user_info.image.thumb.to_s, current_user.user_info.nickname) %>
              <%= current_user.user_info.nickname %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
              <%= link_to t('views.common.navi.regist_post_btn'), new_post_path, class: "dropdown-item" %>
              <%= link_to t('views.common.navi.eidt_user_info_btn'), edit_user_info_path(current_user.user_info.hash_id), class: "dropdown-item" %>
              <%= link_to t('views.common.navi.show_user_pets_btn'), user_pets_user_infos_path(current_user.user_info.hash_id), class: "dropdown-item" %>
              <%= link_to t('views.common.navi.edit_base_info_btn'), edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to t('views.common.navi.logout_btn'), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('views.common.navi.sighup_btn'), new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t('views.common.navi.login_btn'), new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        <!-- !ログイン -->
      </ul>
    </div>
  </div>
</nav>

app/views/common/_post_list.html.erb
<div class="card mb-4">
  <h5 class="card-header"><i class="fa fa-<%= icon_name %>" aria-hidden="true"></i><%= title %></h5>
  <div class="card-body movie-list-s">

    <% posts.each do |post| %>

    <%= render 'common/post_list_item', post: post %>

    <hr class="margin-01">

    <% end %>

  </div>
</div>

app/views/common/_post_list_item.html.erb
<a href="<%= post_path(post.id) %>">
  <div class="row">
    <div class="col-md-5 col-5">
      <a href="<%= post_path post.id %>">
        <img class="img-fluid rounded mb-3 mb-md-0" src="<%= "http://i.ytimg.com/vi/#{post.youtube_video_id}/sddefault.jpg" %>" alt="<%= post.title %>">
      </a>
    </div>
    <div class="col-md-7 col-0">
      <h6>
        <a href="<%= post_path post.id %>" class="normal">
          <%= cut_str post.title, 25 %>
        </a>
      </h6>

      <%= post.impressionist_count %>回閲覧
    </div>
  </div>
</a>

app/views/common/_side_bar_for_guest.html.erb
<% if @recommend_post.present? %>

  <%= render 'common/post_list', title: "オススメ", posts: @recommend_post, icon_name: "thumbs-o-up" %>

<% end %>

<% if @ranking_post.present? %>

  <%= render 'common/post_list', title: "ランキング", posts: @ranking_post, icon_name: "bar-chart-o" %>

<% end %>

app/views/common/_side_bar_for_movie.html.erb
<% if @recommend_post.present? %>

  <%= render 'common/post_list', title: "オススメ", posts: @recommend_post, icon_name: "thumbs-o-up" %>

<% end %>

<% if @ranking_post.present? %>

  <%= render 'common/post_list', title: "ランキング", posts: @ranking_post, icon_name: "bar-chart-o" %>

<% end %>

app/views/common/_side_bar_for_user.html.erb
<div class="col-mb-12">
  <div class="list-group">
    <!-- FIXME: 現在が対象パスの場合はclassに"active"を付与する -->
    <%= link_to t('views.common.side_bar.regist_post_btn'), new_post_path, class: "list-group-item" %>
    <%= link_to t('views.common.side_bar.post_list_btn'), posts_user_infos_path(current_user.user_info.hash_id), class: "list-group-item" %>
    <%= link_to t('views.common.side_bar.eidt_user_info_btn'), edit_user_info_path(current_user.user_info.hash_id), class: "list-group-item" %>
    <%= link_to t('views.common.side_bar.show_user_pets_btn'), user_pets_user_infos_path(current_user.user_info.hash_id), class: "list-group-item" %>
    <%= link_to t('views.common.side_bar.edit_base_info_btn'), edit_user_registration_path, class: "list-group-item" %>
  </div>
</div>
<!-- FIXME: bootsrapのやり方に則り空白を空ける -->
<br>